### ISSUE TITLE
(optional) QP: Advanced Phase I 

### ISSUE THREAD

**Issue by rendstrasser** [rendstrasser/num-opt-group-project-2#21]
Hier gehts um "SPECIFICATION OF THE ACTIVE-SET METHOD FOR CONVEX".

Wir können bereits x0 mit simplex finden, also könnte man argumentieren, wir haben schon die Consideration halbwegs beachtet.
Für SQP könnten wir aber ein x übergeben, welches ein gutes Estimate wäre, vermutlich.
Demnach könnten wir die Phase I Variante wo man x übergeben kann implementieren. 
Das würde ich optional sehen, weil wir aber eh schon das wichtigste (x0 finden) haben.

**Comment by tmpr** [comment]
Ich versuchs mal!
